### ISSUE TITLE
Printing 12 word seed on SH02 Plate?

### ISSUE THREAD

**Issue by nostrbuild** [seedhammer/seedhammer#19]
I don't see a way to print a 12 word seed on a SH2 plate. When I choose '12 word' it automatically puts me on a SH1 plate?
How can I print a 12 word seed on a SH02 plate?

**Comment by seedhammer** [comment]
Thank you for your issue. Unfortunately this is not possible - and nothing we currently plan to support.

The choice of plate size is automatically chosen by the software.

What is the particular reason for your request?

**Comment by nostrbuild** [comment]
Thank you for your response. Reasons are below;
- You discontinued the SH01 2mm plates and understand you will discontinue all SH01 plates.
- Many people will have 12 and 24 word seeds, they shouldn’t have to purchase two different size plates.
- Some people will want all plates to be the same size so they can stack them together, regardless of a 12 or 24 word seed.

**Comment by seedhammer** [comment]
Hi again,

No, we have no plans discontinue SH01-3.

We just move current offerings to 3mm in order to mitigate warp after first side is hammered.

Thank you for your feedback regarding bullet 2 and 3. We will take this into consideration in future iterations, but can't promise anything yet.

Thank you very much.
